### ISSUE TITLE
https://drywall.nodejitsu.com/ is down

### ISSUE THREAD

**Issue by dt-cc** [jedireza/drywall#276]
nodejitsu Demo site appears to be having issues at the moment: https://drywall.nodejitsu.com/

Error: no open connections
    at Db._executeQueryCommand (/opt/run/snapshot/package/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1802:21)
    at Cursor.nextObject (/opt/run/snapshot/package/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:729:13)
    at Cursor.nextObject (/opt/run/snapshot/package/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/scope.js:22:20)
    at Collection.findOne (/opt/run/snapshot/package/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/collection/query.js:145:10)
    at /opt/run/snapshot/package/node_modules/connect-mongo/lib/connect-mongo.js:214:18
    at MongoStore._get_collection (/opt/run/snapshot/package/node_modules/connect-mongo/lib/connect-mongo.js:148:21)
    at MongoStore.get (/opt/run/snapshot/package/node_modules/connect-mongo/lib/connect-mongo.js:213:10)
    at session (/opt/run/snapshot/package/node_modules/express-session/index.js:356:11)
    at Layer.handle [as handle_request] (/opt/run/snapshot/package/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:271:13)

**Comment by jedireza** [comment]
Thanks. It's back up now. Just needed a restart.
