### ISSUE TITLE
csrf issue

### ISSUE THREAD

**Issue by Jonasyao** [jedireza/drywall#323]
Hi,

I have experienced some CSRF issues.

Once I add a group of js lib into the default.jade file in order to make a mobile menu work, there is a csrf issue comes out when I try to login to get to the account page.

```
script(src="/layouts/js/jquery.js")
script(src="/layouts/js/bootstrap.min.js")
script(src="/layouts/js/jquery.easing.js")
script(src="/layouts/js/jquery.flexslider-min.js")
script(src="/layouts/js/jquery.nivo.slider.pack.js")
script(src="/layouts/js/jquery.isotope.min.js")
script(src="/layouts/js/jquery.mCustomScrollbar.concat.min.js")
script(src="/layouts/js/jquery.prettyPhoto.js")
script(src="/layouts/js/animate.js")
script(src="/layouts/js/jquery.fitvids.js")
script(src="/layouts/js/retina.js")
script(src="/layouts/js/respond.min.js")
script(src="/layouts/js/jquery.parallax-1.1.3.js")
script(src="/layouts/js/jquery.refineslide.js")
script(src="/layouts/js/selectnav.js")
script(src="/layouts/js/functions.js")
```

```
ForbiddenError: invalid csrf token
        at verifytoken (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/csurf/index.js:269:11)
        at csrf (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/csurf/index.js:97:7)
        at Layer.handle [as handle_request] (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/index.js:312:13)
        at /home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/index.js:280:7
        at Function.process_params (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/index.js:330:12)
        at next (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/index.js:271:10)
        at SessionStrategy.strategy.pass (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/passport/lib/middleware/authenticate.js:318:9)
        at SessionStrategy.authenticate (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/passport/lib/strategies/session.js:67:10)
        at attempt (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/passport/lib/middleware/authenticate.js:341:16)
        at authenticate (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/passport/lib/middleware/authenticate.js:342:7)
        at Layer.handle [as handle_request] (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/index.js:312:13)
        at /home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/index.js:280:7
        at Function.process_params (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/index.js:330:12)
        at next (/home/jyao/Desktop/XinViteerManagement/drywall/node_modules/express/lib/router/index.js:271:10)
    POST /login/ 500 10.622 ms - 76
```
 
I really appreciate if there is any help on this.

**Comment by jedireza** [comment]
Thanks for creating an issue. I get the sense that you're over looking the build pipeline. The build pipeline is responsible for packing up our JS and CSS. You should get familiar with:
https://github.com/jedireza/drywall/blob/master/Gruntfile.js

Regarding CSRF:

Server side we send the csrf token in this middleware:
https://github.com/jedireza/drywall/blob/ca35c06bf5100d2835da929bd1bd3c39ae441138/app.js#L63

And on the client we inject the csrf token using jQuery's `beforeSend` function here:
https://github.com/jedireza/drywall/blob/ca35c06bf5100d2835da929bd1bd3c39ae441138/public/layouts/core.js#L16-L20

**Comment by harshalbagul-cse** [comment]
I have test the API using POSTMAN, but its gives me a following error.

Post Call: localhost:3000/login
`ForbiddenError: invalid csrf token`

![untitled](https://cloud.githubusercontent.com/assets/13729158/12710426/94f2ada2-c8dc-11e5-9ba2-ba97d0e15f4b.png)

**Comment by jedireza** [comment]
@harshalbagul-cse please create new issues instead of posting on old closed ones. To help answer your question:

The csrf token is sent to the client via a cookie and then sent back to the server via request headers. We do this on the client side here:

https://github.com/jedireza/drywall/blob/d6d6d7b1fb036f927a6cd3f5e6a1717683e50614/public/layouts/core.js#L16-L20

We're using the [`csurf`](https://github.com/expressjs/csurf) module for this. Please read the docs and study how we've implemented it and customize as needed.

**Comment by harshalbagul-cse** [comment]
@jedireza Thanks for reply. Im trying to solve that issue but cant overcome it. I have to read the docs regarding `csurf` module. Hope so I solve this issue.
