### ISSUE TITLE
Step by step to build the project and have problem

### ISSUE THREAD

**Issue by GabrielchenCN** [jedireza/drywall#332]
![image](https://cloud.githubusercontent.com/assets/11185797/11835421/59736a0c-a40e-11e5-9d2f-3c068345c746.png)
![image](https://cloud.githubusercontent.com/assets/11185797/11835432/71163aa4-a40e-11e5-8fb1-fbee066f3617.png)
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart Drywall@0.16.4
6 info start Drywall@0.16.4
7 verbose unsafe-perm in lifecycle true
8 info Drywall@0.16.4 Failed to exec start script
9 verbose stack Error: Drywall@0.16.4 start: `grunt`
9 verbose stack Exit status 3
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid Drywall@0.16.4
11 verbose cwd /Users/../drywall
12 error Darwin 15.0.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.2.3
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error Drywall@0.16.4 start: `grunt`
17 error Exit status 3
18 error Failed at the Drywall@0.16.4 start script 'grunt'.
18 error This is most likely a problem with the Drywall package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt
18 error You can get their info via:
18 error     npm owner ls Drywall
18 error There is likely additional logging output above.

npm version
{ Drywall: '0.16.4',
  npm: '2.14.7',
  node: 'v4.2.3',
  }

when i execute the code of npm install ，it tell me warn about graceful-fs 、inherits。when i start the drywall ， it tell me can not find inherits 、 graceful－fs and etc，so i exec the npm to install them， but i
got the  same result as above

**Comment by GabrielchenCN** [comment]
i fixed the problem , by https://github.com/jedireza/drywall/issues/329 and http://stackoverflow.com/questions/20764881/why-does-npm-install-say-i-have-unmet-dependencies
