### ISSUE TITLE
I am getting a Use of const in strict mode.' error

### ISSUE THREAD

**Issue by linked-2** [jedireza/drywall#353]
Hi this might be something super simple - hope you dont mind me posting a question. I followed your installation instructions and I am getting an error.  Any help appreciated.

```
{ Drywall: '0.17.0',
  npm: '2.5.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }
```

here is the full error:

```
    /Users/mark07/drywall-master/node_modules/connect-mongo/src/index.js:3
    const Promise = require('bluebird');
    ^^^^^
    SyntaxError: Use of const in strict mode.
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/mark07/drywall-master/node_modules/connect-mongo/index.js:1:80)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
```

**Comment by linked-2** [comment]
I figured this out. I was running Node .12 - duh. Upgraded Node - now everything is working fine.

**Comment by jedireza** [comment]
Yup that'll do it :wink:
