### ISSUE TITLE
CSRF issue / new form issue

### ISSUE THREAD

**Issue by sturad** [jedireza/drywall#362]
Hi,  

I am trying to create new form for a client's fork of Drywall.  The form simply will update a custom field on the User when we submit it for accepting terms and conditions.   When my Post handler receives the form it dies on on invalid CSRF token.  The form is not a Backbone view which might be  causing the underlying problem.   

```
node_modules/csurf/index.js:235

 function verifytoken(req, tokens, secret, val) {
// valid token
 if (!tokens.verify(secret, val)) {
```
val is nul in this case.

```
at verifytoken (/Users/sraden/code/drywall-app/node_modules/csurf/index.js:238:11)
at csrf (/Users/sraden/code/drywall-app/node_modules/csurf/index.js:100:7)
at Layer.handle [as handle_request] (/Users/sraden/code/drywall-app/node_modules/express/lib/router/layer.js:82:5)
at trim_prefix (/Users/sraden/code/drywall-app/node_modules/express/lib/router/index.js:302:13)
at proto.handle.c (/Users/sraden/code/drywall-app/node_modules/express/lib/router/index.js:270:7)
at Function.proto.process_params (/Users/sraden/code/drywall-app/node_modules/express/lib/router/index.js:321:12)
at next (/Users/sraden/code/drywall-app/node_modules/express/lib/router/index.js:261:10)
at SessionStrategy.module.exports.strategy.pass (/Users/sraden/code/drywall-app/node_modules/passport/lib/middleware/authenticate.js:318:9)
at SessionStrategy.authenticate (/Users/sraden/code/drywall-app/node_modules/passport/lib/strategies/session.js:61:12)
at pass (/Users/sraden/code/drywall-app/node_modules/passport/lib/authenticator.js:333
```

So I'm hoping to understand what doe we need to do to add a new form to a Drywall application and make use of the CSRF protection already built in.  Thanks.

**Comment by sturad** [comment]
Also of note here:

1. csrf _csrfToken are populated in the request header Cookie on the form page. 
2. Response header Set-Cookie has _csrfToken populated. 
3. This line of core.js does  fire when the form page loads

 $.ajaxSetup({
      beforeSend: function (xhr) {
        xhr.setRequestHeader('x-csrf-token', $.cookie('_csrfToken'));
      }
    });

This last bit makes wonder if  that I need to set up the form as Backbone view (or otherwise submit with ajax )  to benefit the CSRF stuff built into Drywall.

**Comment by sturad** [comment]
I can confirm I got past this CSRF issue with a ajax form submit I think a wiki page on creating an arbitrary CRUD page could be good (unless I missed existing one).  I'm happy to help write it,  but I don't know Backbone very well.

**Comment by jedireza** [comment]
Thanks for opening an issue. Take a look at #323 and see if that helps.

**Comment by sturad** [comment]
Yes, looking at the call xhr.setRequestHeader() mentioned in that issue confirmed I should be submitting the form on submit and that got past the specific issue.
